name: Build & Deploy

on:
  push:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Code
        uses: actions/checkout@v2
            
      - name: Run Application
        run: node server.js
        env:
          TOKEN: ${{ secrets.TOKEN }}